steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/engagement-app-288317/engagement-app-image', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/engagement-app-288317/engagement-app-image']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'engagement-app-image', '--image', 'gcr.io/engagement-app-288317/engagement-app-image', '--region', 'asia-east1']
